version = "3.11.1"
runner.dialect = scala3

maxColumn = 100
align.preset = more
continuationIndent.defnSite = 2

rewrite.rules = [
  Imports,
  SortModifiers
]

trailingCommas = always

rewrite.imports.sort = scalastyle

# Automatically strips out unnecessary old 'then' and 'do' tokens
rewrite.scala3.removeOptionalBraces = true

# Forces standardisation of old-style function arrows to modern tokens
rewrite.scala3.convertToNewSyntax = true
