rules = [
  OrganizeImports,
]

OrganizeImports {
  expandRelative = true
  preset = DEFAULT
  removeUnused = true
  groups = [
    "play.",
    "re:(action.|config.|controllers.|forms.|implicits.|models.|modules.|persistence.|services.|views.)",
    "re:javax?\\.",
    "scala."]
  groupedImports = Merge
  targetDialect = Scala3
}
