services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: personal_finance_tracker
      POSTGRES_USER: pft_app
      POSTGRES_PASSWORD: finance
    ports:
      - 5432:5432
    volumes:
      - pft_postgres_data:/var/lib/postgresql 
  db-test:
    image: postgres:18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: personal_finance_tracker_test
      POSTGRES_USER: pft_app
      POSTGRES_PASSWORD: finance
    ports:
      - 5433:5432
    tmpfs:
      - /var/lib/postgresql


volumes:
  pft_postgres_data:
      
      