db.default {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/personal_finance_tracker"
  username = "pft_app"
  password = "finance"
  poolSize = 8
  migration.auto = true
}

db.default {
  url = ${?DATABASE_URL}
  user = ${?DATABASE_USERNAME}
  password = ${?DATABASE_PASSWORD}
}

play.http.secret.key = "setnsnthaernshtn2u3lu2oasltxzcvacxvxa"
play.http.secret.key = ${?SECRET_KEY}

play.modules.enabled += "org.flywaydb.play.PlayModule"
play.modules.enabled += "modules.DatabaseModule"
