# https://www.playframework.com/documentation/latest/Configuration

db.default {
  url = "localhost:db"
  user = "adambanner"
  password = "password"
}

db.default {
  url = ${?DATABASE_URL}
  user = ${?DATABASE_USERNAME}
  password = ${?DATABASE_PASSWORD}
}

play.http.secret.key = "default secret key"
play.http.secret.key = ${?SECRET_KEY}