include "application.conf"

play.http.session.secure = true

play.http.secret.key = ${?APPLICATION_SECRET}

db.default {
  url = ${?DATABASE_URL}
  user = ${?DATABASE_USERNAME}
  password = ${?DATABASE_PASSWORD}
}