db.default {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/personal_finance_tracker"
  username = "pft_app"
  password = "finance"
  poolSize = 8
  migration.auto = true
}

play.http.session {
  httpOnly = true
  sameSite = "lax"
  secure = false
}

play.modules.enabled += "modules.DatabaseModule"
play.modules.enabled += "modules.AuthModule"
